In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('Data1.csv')
x = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

**Logistic Model**

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
pred = classifier.predict(x_test)
cm1 = confusion_matrix(y_test,pred)
print(cm1)
accuracy_score(y_test,pred)

[[103   4]
 [  5  59]]


0.9473684210526315

**KNN Model**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
cls = KNeighborsClassifier(n_neighbors = 5 , metric= 'minkowski' , p = 2)
cls.fit(x_train,y_train) 

KNeighborsClassifier()

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
pred2 = cls.predict(x_test)
cm2 = confusion_matrix(y_test,pred2)
print(cm2)
accuracy_score(y_test,pred2)

[[103   4]
 [  4  60]]


0.9532163742690059

**Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
cls2 = GaussianNB()
cls2.fit(x_train,y_train)

GaussianNB()

In [ ]:
pred3 = cls2.predict(x_test)
cm3 = confusion_matrix(y_test,pred3)
print(cm3)
accuracy_score(y_test,pred3) 

[[99  8]
 [ 2 62]]


0.9415204678362573

**Decision Tree Model**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
cls3 = DecisionTreeClassifier(criterion='entropy' , random_state = 0)
cls3.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
pred4 = cls3.predict(x_test)
print(confusion_matrix(y_test,pred4))
accuracy_score(y_test,pred4) 

[[104   3]
 [  4  60]]


0.9590643274853801

**Random Forest Model**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
cls4 = RandomForestClassifier(n_estimators= 10,criterion = 'entropy' , random_state = 0)
cls4.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
pred5 = cls4.predict(x_test)
print(confusion_matrix(y_test,pred5))
accuracy_score(y_test,pred5)

[[104   3]
 [  5  59]]


0.9532163742690059

**SVM Model**

In [ ]:
from sklearn.svm import SVC
cls5 = SVC(kernel='linear',random_state= 0)
cls5.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
pred6 = cls5.predict(x_test)
print(confusion_matrix(y_test,pred6)) 
accuracy_score(y_test,pred6) 

[[102   5]
 [  5  59]]


0.9415204678362573

**Kernel SVM**

In [ ]:
from sklearn.svm import SVC
cls6 = SVC(kernel='rbf',random_state = 0)
cls6.fit(x_train,y_train)

SVC(random_state=0)

In [ ]:
pred7 = cls6.predict(x_test)
print(confusion_matrix(y_test,pred7))
accuracy_score(y_test,pred6)

[[102   5]
 [  3  61]]


0.9415204678362573

 **As Accuracy Score of Decision Tree is Higher that mean DTM is more accurate** 